// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
// 04515 — Scene Constants
// Configuration data for the 3D visualization
// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

import type { OasisSettings, AssetDefinition } from './types'

// ═══════════════════════════════════════════════════════════════════════════════
// DEFAULT SETTINGS
// ═══════════════════════════════════════════════════════════════════════════════

export const defaultSettings: OasisSettings = {
  bloomEnabled: true,
  vignetteEnabled: true,
  chromaticEnabled: false,
  showOrbitTarget: true,      // Show orbit pivot sphere
  skyBackground: 'night007',
  uiOpacity: 0.3,            // Transparent UI — lets the 3D world breathe
  // FPS COUNTER
  fpsCounterEnabled: true,
  fpsCounterFontSize: 14,
  // WINDOW OPACITY
  streamOpacity: 0.9,
  // QUAKE FPS CONTROLS
  controlMode: 'fps',         // FPS mode — gamers gonna game
  mouseSensitivity: 1.0,      // FPS mouse sensitivity (0.1-2.0)
  moveSpeed: 10,              // FPS movement speed (1-20)
}

// ═══════════════════════════════════════════════════════════════════════════════
// SKY BACKGROUNDS — Night panoramas + Poly Haven HDRIs + drei presets
// ═══════════════════════════════════════════════════════════════════════════════

export const SKY_BACKGROUNDS = [
  { id: 'stars', name: 'Procedural Stars', path: null },
  // Local night sky JPGs (4K tonemapped)
  { id: 'night001', name: 'Night Sky 001', path: '/hdri/NightSkyHDRI001_4K_TONEMAPPED.jpg' },
  { id: 'night004', name: 'Night Sky 004', path: '/hdri/NightSkyHDRI004_4K_TONEMAPPED.jpg' },
  { id: 'night007', name: 'Night Sky 007', path: '/hdri/NightSkyHDRI007_4K_TONEMAPPED.jpg' },
  { id: 'night008', name: 'Night Sky 008', path: '/hdri/NightSkyHDRI008_4K_TONEMAPPED.jpg' },
  // Poly Haven HDRIs (2K .hdr — true HDR lighting + background)
  { id: 'alps_field', name: 'Alps Field', path: '/hdri/alps_field_2k.hdr' },
  { id: 'autumn_ground', name: 'Autumn Ground', path: '/hdri/autumn_ground_2k.hdr' },
  { id: 'belfast_sunset', name: 'Belfast Sunset', path: '/hdri/belfast_sunset_puresky_2k.hdr' },
  { id: 'blue_grotto', name: 'Blue Grotto', path: '/hdri/blue_grotto_2k.hdr' },
  { id: 'evening_road', name: 'Evening Road', path: '/hdri/evening_road_01_puresky_2k.hdr' },
  { id: 'outdoor_umbrellas', name: 'Outdoor Umbrellas', path: '/hdri/outdoor_umbrellas_2k.hdr' },
  { id: 'stadium', name: 'Stadium', path: '/hdri/stadium_01_2k.hdr' },
  { id: 'sunny_vondelpark', name: 'Sunny Vondelpark', path: '/hdri/sunny_vondelpark_2k.hdr' },
  // drei built-in presets (CDN-hosted 1k HDRIs — may fail in production)
  { id: 'city', name: 'City (Potsdamer Platz)', path: null, preset: 'city' },
  { id: 'dawn', name: 'Dawn', path: null, preset: 'dawn' },
  { id: 'forest', name: 'Forest', path: null, preset: 'forest' },
  { id: 'sunset', name: 'Sunset (Venice)', path: null, preset: 'sunset' },
  { id: 'park', name: 'Park', path: null, preset: 'park' },
  { id: 'night_preset', name: 'Night (Dikhololo)', path: null, preset: 'night' },
  { id: 'studio', name: 'Studio', path: null, preset: 'studio' },
  { id: 'warehouse', name: 'Warehouse', path: null, preset: 'warehouse' },
  { id: 'apartment', name: 'Apartment (Lobby)', path: null, preset: 'apartment' },
  { id: 'lobby', name: 'Lobby (St Fagans)', path: null, preset: 'lobby' },
] as const

// ═══════════════════════════════════════════════════════════════════════════════
// ASSET CATALOG — All available 3D models for the explorer
// 565 assets: Quaternius (Cyberpunk + SciFi + Fantasy + Medieval Village) + Kenney (Medieval + Urban + Furniture)
// ═══════════════════════════════════════════════════════════════════════════════

export const ASSET_CATALOG: AssetDefinition[] = [

  // ─═══─ PLATFORMS (Quaternius Cyberpunk Kit) ─═══─
  { id: 'antenna1', name: 'Antenna 1', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Antenna_1.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'antenna2', name: 'Antenna 2', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Antenna_2.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'ac', name: 'AC Unit', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/AC.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'ac_side', name: 'AC Side', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/AC_Side.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'ac_stacked', name: 'AC Stacked', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/AC_Stacked.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'cable_long', name: 'Cable Long', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Cable_Long.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'cable_small', name: 'Cable Small', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Cable_Small.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'cable_thick', name: 'Cable Thick', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Cable_Thick.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'computer', name: 'Computer', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Computer.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'computer_large', name: 'Computer Large', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Computer_Large.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'door', name: 'Door', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Door.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'fence', name: 'Fence', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Fence.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'light_square', name: 'Light Square', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Light_Square.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'light_street1', name: 'Street Light 1', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Light_Street_1.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'light_street2', name: 'Street Light 2', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Light_Street_2.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'pipe1', name: 'Pipe 1', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Pipe_1.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'pipe2', name: 'Pipe 2', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Pipe_2.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'pipe_corner', name: 'Pipe Corner', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Pipe_Corner.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'pipe_corner2', name: 'Pipe Corner 2', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Pipe_Corner_2.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'platform_1x1', name: 'Platform 1x1', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Platform_1x1_Empty.gltf', category: 'platforms', defaultScale: 1 },
  { id: 'platform_2x1', name: 'Platform 2x1', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Platform_2x1_Empty.gltf', category: 'platforms', defaultScale: 1 },
  { id: 'platform_2x2', name: 'Platform 2x2', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Platform_2x2.gltf', category: 'platforms', defaultScale: 1 },
  { id: 'platform_2x2_empty', name: 'Platform 2x2 Empty', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Platform_2x2_Empty.gltf', category: 'platforms', defaultScale: 1 },
  { id: 'platform_4x1', name: 'Platform 4x1', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Platform_4x1.gltf', category: 'platforms', defaultScale: 1 },
  { id: 'platform_4x1_empty', name: 'Platform 4x1 Empty', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Platform_4x1_Empty.gltf', category: 'platforms', defaultScale: 1 },
  { id: 'platform_4x2', name: 'Platform 4x2', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Platform_4x2.gltf', category: 'platforms', defaultScale: 1 },
  { id: 'platform_4x4', name: 'Platform 4x4', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Platform_4x4.gltf', category: 'platforms', defaultScale: 1 },
  { id: 'platform_4x4_empty', name: 'Platform 4x4 Empty', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Platform_4x4_Empty.gltf', category: 'platforms', defaultScale: 1 },
  { id: 'rail_corner', name: 'Rail Corner', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Rail_Corner.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'rail_corner2', name: 'Rail Corner 2', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Rail_Corner_2.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'rail_long', name: 'Rail Long', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Rail_Long.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'rail_short', name: 'Rail Short', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Rail_Short.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'sign1', name: 'Sign 1', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_1.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'sign2', name: 'Sign 2', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_2.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'sign3', name: 'Sign 3', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_3.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'sign4', name: 'Sign 4', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_4.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'sign_corner1', name: 'Sign Corner 1', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_Corner_1.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'sign_corner2', name: 'Sign Corner 2', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_Corner_2.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'sign_corner3', name: 'Sign Corner 3', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_Corner_3.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'sign_corner3_fenced', name: 'Sign Corner Fenced', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_Corner_3_Fenced.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'sign_corner_hazard', name: 'Sign Hazard', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_Corner_Hazard.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'sign_corner_small1', name: 'Sign Small 1', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_Corner_Small1.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'sign_corner_small2', name: 'Sign Small 2', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_Corner_Small2.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'sign_small1', name: 'Sign Mini 1', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_Small_1.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'sign_small2', name: 'Sign Mini 2', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_Small_2.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'sign_small3', name: 'Sign Mini 3', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Sign_Small_3.gltf', category: 'platforms', defaultScale: 1.5 },
  { id: 'support', name: 'Support', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Support.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'support_long', name: 'Support Long', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Support_Long.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'support_short', name: 'Support Short', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/Support_Short.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'tv1', name: 'TV 1', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/TV_1.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'tv2', name: 'TV 2', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/TV_2.gltf', category: 'platforms', defaultScale: 2 },
  { id: 'tv3', name: 'TV 3', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Platforms/TV_3.gltf', category: 'platforms', defaultScale: 2 },

  // ─═══─ ENEMIES (Quaternius Cyberpunk + Sci-Fi) ─═══─
  { id: 'enemy_2legs', name: '2-Leg Robot', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Enemies/Enemy_2Legs.gltf', category: 'enemies', defaultScale: 1.5 },
  { id: 'enemy_2legs_gun', name: '2-Leg Robot (Gun)', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Enemies/Enemy_2Legs_Gun.gltf', category: 'enemies', defaultScale: 1.5 },
  { id: 'enemy_flying', name: 'Flying Enemy', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Enemies/Enemy_Flying.gltf', category: 'enemies', defaultScale: 1.5 },
  { id: 'enemy_flying_gun', name: 'Flying Enemy (Gun)', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Enemies/Enemy_Flying_Gun.gltf', category: 'enemies', defaultScale: 1.5 },
  { id: 'enemy_large', name: 'Large Robot', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Enemies/Enemy_Large.gltf', category: 'enemies', defaultScale: 1.5 },
  { id: 'enemy_large_gun', name: 'Large Robot (Gun)', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Enemies/Enemy_Large_Gun.gltf', category: 'enemies', defaultScale: 1.5 },
  { id: 'turret_cannon', name: 'Turret Cannon', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Enemies/Turret_Cannon.gltf', category: 'enemies', defaultScale: 1.5 },
  { id: 'turret_gun', name: 'Turret Gun', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Enemies/Turret_Gun.gltf', category: 'enemies', defaultScale: 1.5 },
  { id: 'turret_double', name: 'Turret Double', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Enemies/Turret_GunDouble.gltf', category: 'enemies', defaultScale: 1.5 },
  { id: 'turret_teleporter', name: 'Turret Teleporter', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Enemies/Turret_Teleporter.gltf', category: 'enemies', defaultScale: 1.5 },
  { id: 'enemy_eyedrone', name: 'Eye Drone', path: '/models/scifi-essentials/Enemy_EyeDrone.gltf', category: 'enemies', defaultScale: 1.5 },
  { id: 'enemy_quadshell', name: 'Quad Shell', path: '/models/scifi-essentials/Enemy_QuadShell.gltf', category: 'enemies', defaultScale: 1.5 },
  { id: 'enemy_trilobite', name: 'Trilobite', path: '/models/scifi-essentials/Enemy_Trilobite.gltf', category: 'enemies', defaultScale: 1.5 },

  // ─═══─ PICKUPS (Quaternius Cyberpunk) ─═══─
  { id: 'board', name: 'Collectible Board', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Pickups and Objects/Collectible_Board.gltf', category: 'pickups', defaultScale: 2 },
  { id: 'gear', name: 'Collectible Gear', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Pickups and Objects/Collectible_Gear.gltf', category: 'pickups', defaultScale: 3 },
  { id: 'lever', name: 'Lever', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Pickups and Objects/Lever.gltf', category: 'pickups', defaultScale: 2 },
  { id: 'lootbox', name: 'Lootbox', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Pickups and Objects/Lootbox.gltf', category: 'pickups', defaultScale: 2.5 },
  { id: 'health', name: 'Health Pickup', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Pickups and Objects/Pickup_Health.gltf', category: 'pickups', defaultScale: 2 },
  { id: 'heart', name: 'Heart Pickup', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Pickups and Objects/Pickup_Heart.gltf', category: 'pickups', defaultScale: 2 },
  { id: 'pickup_tank', name: 'Tank Pickup', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Pickups and Objects/Pickup_Tank.gltf', category: 'pickups', defaultScale: 2 },
  { id: 'tank', name: 'Tank', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Pickups and Objects/Tank.gltf', category: 'pickups', defaultScale: 2 },

  // ─═══─ CHARACTER (Quaternius Cyberpunk) ─═══─
  { id: 'character', name: 'Character', path: '/models/cyberpunk/Cyberpunk Game Kit - Quaternius/Character/Character.gltf', category: 'character', defaultScale: 1.5 },

  // ─═══─ GUNS (Quaternius Sci-Fi Essentials) ─═══─
  { id: 'gun_pistol', name: 'Pistol', path: '/models/scifi-essentials/Gun_Pistol.gltf', category: 'guns', defaultScale: 2 },
  { id: 'gun_revolver', name: 'Revolver', path: '/models/scifi-essentials/Gun_Revolver.gltf', category: 'guns', defaultScale: 2 },
  { id: 'gun_rifle', name: 'Rifle', path: '/models/scifi-essentials/Gun_Rifle.gltf', category: 'guns', defaultScale: 2 },
  { id: 'gun_smg', name: 'SMG', path: '/models/scifi-essentials/Gun_SMG_Ammo.gltf', category: 'guns', defaultScale: 2 },
  { id: 'gun_sniper', name: 'Sniper', path: '/models/scifi-essentials/Gun_Sniper.gltf', category: 'guns', defaultScale: 2 },
  { id: 'gun_sniper_ammo', name: 'Sniper Ammo', path: '/models/scifi-essentials/Gun_Sniper_Ammo.gltf', category: 'guns', defaultScale: 2 },

  // ─═══─ PROPS (Quaternius Sci-Fi Essentials) ─═══─
  { id: 'prop_ammo', name: 'Ammo Box', path: '/models/scifi-essentials/Prop_Ammo.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_ammo_closed', name: 'Ammo Box Closed', path: '/models/scifi-essentials/Prop_Ammo_Closed.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_ammo_small', name: 'Ammo Small', path: '/models/scifi-essentials/Prop_Ammo_Small.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_barrel1', name: 'Barrel 1', path: '/models/scifi-essentials/Prop_Barrel1.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_barrel2_closed', name: 'Barrel 2 Closed', path: '/models/scifi-essentials/Prop_Barrel2_Closed.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_barrel2_open', name: 'Barrel 2 Open', path: '/models/scifi-essentials/Prop_Barrel2_Open.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_chair', name: 'Chair', path: '/models/scifi-essentials/Prop_Chair.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_chest', name: 'Chest', path: '/models/scifi-essentials/Prop_Chest.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_crate', name: 'Crate', path: '/models/scifi-essentials/Prop_Crate.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_crate_large', name: 'Crate Large', path: '/models/scifi-essentials/Prop_Crate_Large.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_crate_tarp', name: 'Crate Tarp', path: '/models/scifi-essentials/Prop_Crate_Tarp.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_crate_tarp_large', name: 'Crate Tarp Large', path: '/models/scifi-essentials/Prop_Crate_Tarp_Large.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_desk_l', name: 'Desk L', path: '/models/scifi-essentials/Prop_Desk_L.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_desk_medium', name: 'Desk Medium', path: '/models/scifi-essentials/Prop_Desk_Medium.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_desk_small', name: 'Desk Small', path: '/models/scifi-essentials/Prop_Desk_Small.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_grenade', name: 'Grenade', path: '/models/scifi-essentials/Prop_Grenade.gltf', category: 'props', defaultScale: 3 },
  { id: 'prop_healthpack', name: 'Health Pack', path: '/models/scifi-essentials/Prop_HealthPack.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_healthpack_tube', name: 'Health Tube', path: '/models/scifi-essentials/Prop_HealthPack_Tube.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_keycard', name: 'Keycard', path: '/models/scifi-essentials/Prop_KeyCard.gltf', category: 'props', defaultScale: 3 },
  { id: 'prop_locker', name: 'Locker', path: '/models/scifi-essentials/Prop_Locker.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_mine', name: 'Mine', path: '/models/scifi-essentials/Prop_Mine.gltf', category: 'props', defaultScale: 3 },
  { id: 'prop_mug', name: 'Mug', path: '/models/scifi-essentials/Prop_Mug.gltf', category: 'props', defaultScale: 3 },
  { id: 'prop_satellite', name: 'Satellite Dish', path: '/models/scifi-essentials/Prop_SatelliteDish.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_shelves_thin_short', name: 'Shelves Thin Short', path: '/models/scifi-essentials/Prop_Shelves_ThinShort.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_shelves_thin_tall', name: 'Shelves Thin Tall', path: '/models/scifi-essentials/Prop_Shelves_ThinTall.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_shelves_wide_short', name: 'Shelves Wide Short', path: '/models/scifi-essentials/Prop_Shelves_WideShort.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_shelves_wide_tall', name: 'Shelves Wide Tall', path: '/models/scifi-essentials/Prop_Shelves_WideTall.gltf', category: 'props', defaultScale: 2 },
  { id: 'prop_syringe', name: 'Syringe', path: '/models/scifi-essentials/Prop_Syringe.gltf', category: 'props', defaultScale: 3 },

  // ─═══─ MEDIEVAL (Kenney Retro Medieval Kit — 105 GLBs, CC0) ─═══─
  { id: 'km_barrels', name: 'Barrels', path: '/models/kenney-medieval/barrels.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_battlement', name: 'Battlement', path: '/models/kenney-medieval/battlement.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_battlement_corner_in', name: 'Battlement Corner Inner', path: '/models/kenney-medieval/battlement-corner-inner.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_battlement_corner_out', name: 'Battlement Corner Outer', path: '/models/kenney-medieval/battlement-corner-outer.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_battlement_half', name: 'Battlement Half', path: '/models/kenney-medieval/battlement-half.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_bricks', name: 'Bricks', path: '/models/kenney-medieval/bricks.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_column', name: 'Column', path: '/models/kenney-medieval/column.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_column_damaged', name: 'Column Damaged', path: '/models/kenney-medieval/column-damaged.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_column_paint', name: 'Column Paint', path: '/models/kenney-medieval/column-paint.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_column_paint_dmg', name: 'Column Paint Damaged', path: '/models/kenney-medieval/column-paint-damaged.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_column_wood', name: 'Column Wood', path: '/models/kenney-medieval/column-wood.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_barrel', name: 'Barrel', path: '/models/kenney-medieval/detail-barrel.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_crate', name: 'Crate', path: '/models/kenney-medieval/detail-crate.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_crate_ropes', name: 'Crate Ropes', path: '/models/kenney-medieval/detail-crate-ropes.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_crate_small', name: 'Crate Small', path: '/models/kenney-medieval/detail-crate-small.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_dock_corner', name: 'Dock Corner', path: '/models/kenney-medieval/dock-corner.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_dock_side', name: 'Dock Side', path: '/models/kenney-medieval/dock-side.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_fence_med', name: 'Fence', path: '/models/kenney-medieval/fence.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_fence_top', name: 'Fence Top', path: '/models/kenney-medieval/fence-top.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_fence_wood', name: 'Fence Wood', path: '/models/kenney-medieval/fence-wood.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_floor', name: 'Floor', path: '/models/kenney-medieval/floor.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_floor_flat', name: 'Floor Flat', path: '/models/kenney-medieval/floor-flat.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_floor_stairs', name: 'Floor Stairs', path: '/models/kenney-medieval/floor-stairs.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_floor_stairs_ci', name: 'Floor Stairs Corner In', path: '/models/kenney-medieval/floor-stairs-corner-inner.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_floor_stairs_co', name: 'Floor Stairs Corner Out', path: '/models/kenney-medieval/floor-stairs-corner-outer.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_floor_steps', name: 'Floor Steps', path: '/models/kenney-medieval/floor-steps.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_floor_steps_ci', name: 'Floor Steps Corner In', path: '/models/kenney-medieval/floor-steps-corner-inner.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_floor_steps_co', name: 'Floor Steps Corner Out', path: '/models/kenney-medieval/floor-steps-corner-outer.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_ladder', name: 'Ladder', path: '/models/kenney-medieval/ladder.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_overhang', name: 'Overhang', path: '/models/kenney-medieval/overhang.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_overhang_fence', name: 'Overhang Fence', path: '/models/kenney-medieval/overhang-fence.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_overhang_round', name: 'Overhang Round', path: '/models/kenney-medieval/overhang-round.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_overhang_round_rail', name: 'Overhang Round Rail', path: '/models/kenney-medieval/overhang-round-railing.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_pulley', name: 'Pulley', path: '/models/kenney-medieval/pulley.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_pulley_crate', name: 'Pulley Crate', path: '/models/kenney-medieval/pulley-crate.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_roof', name: 'Roof', path: '/models/kenney-medieval/roof.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_roof_corner', name: 'Roof Corner', path: '/models/kenney-medieval/roof-corner.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_roof_edge', name: 'Roof Edge', path: '/models/kenney-medieval/roof-edge.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_roof_high_side', name: 'Roof High Side', path: '/models/kenney-medieval/roof-high-side.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_roof_high_side_c', name: 'Roof High Side Corner', path: '/models/kenney-medieval/roof-high-side-corner.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_roof_high_side_ci', name: 'Roof High Side Corner In', path: '/models/kenney-medieval/roof-high-side-corner-inner.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_roof_side', name: 'Roof Side', path: '/models/kenney-medieval/roof-side.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_roof_side_c', name: 'Roof Side Corner', path: '/models/kenney-medieval/roof-side-corner.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_roof_side_ci', name: 'Roof Side Corner In', path: '/models/kenney-medieval/roof-side-corner-inner.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_stairs_corner', name: 'Stairs Corner', path: '/models/kenney-medieval/stairs-corner.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_stairs_stone', name: 'Stairs Stone', path: '/models/kenney-medieval/stairs-stone.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_stairs_wood', name: 'Stairs Wood', path: '/models/kenney-medieval/stairs-wood.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_structure', name: 'Structure', path: '/models/kenney-medieval/structure.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_structure_cross', name: 'Structure Cross', path: '/models/kenney-medieval/structure-cross.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_structure_pole', name: 'Structure Pole', path: '/models/kenney-medieval/structure-pole.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_structure_poles', name: 'Structure Poles', path: '/models/kenney-medieval/structure-poles.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_structure_wall', name: 'Structure Wall', path: '/models/kenney-medieval/structure-wall.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_structure_wall_x', name: 'Structure Wall Cross', path: '/models/kenney-medieval/structure-wall-cross.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_tower', name: 'Tower', path: '/models/kenney-medieval/tower.glb', category: 'structures', defaultScale: 2 },
  { id: 'km_tower_base', name: 'Tower Base', path: '/models/kenney-medieval/tower-base.glb', category: 'structures', defaultScale: 2 },
  { id: 'km_tower_edge', name: 'Tower Edge', path: '/models/kenney-medieval/tower-edge.glb', category: 'structures', defaultScale: 2 },
  { id: 'km_tower_paint', name: 'Tower Paint', path: '/models/kenney-medieval/tower-paint.glb', category: 'structures', defaultScale: 2 },
  { id: 'km_tower_paint_base', name: 'Tower Paint Base', path: '/models/kenney-medieval/tower-paint-base.glb', category: 'structures', defaultScale: 2 },
  { id: 'km_tower_top', name: 'Tower Top', path: '/models/kenney-medieval/tower-top.glb', category: 'structures', defaultScale: 2 },
  { id: 'km_tree_large', name: 'Tree Large', path: '/models/kenney-medieval/tree-large.glb', category: 'nature', defaultScale: 2 },
  { id: 'km_tree_shrub', name: 'Shrub', path: '/models/kenney-medieval/tree-shrub.glb', category: 'nature', defaultScale: 2 },
  { id: 'km_wall', name: 'Wall', path: '/models/kenney-medieval/wall.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_detail', name: 'Wall Detail', path: '/models/kenney-medieval/wall-detail.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_door', name: 'Wall Door', path: '/models/kenney-medieval/wall-door.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_flat_gate', name: 'Wall Flat Gate', path: '/models/kenney-medieval/wall-flat-gate.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_fortified', name: 'Wall Fortified', path: '/models/kenney-medieval/wall-fortified.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_fort_door', name: 'Wall Fort Door', path: '/models/kenney-medieval/wall-fortified-door.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_fort_gate', name: 'Wall Fort Gate', path: '/models/kenney-medieval/wall-fortified-gate.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_fort_gate_h', name: 'Wall Fort Gate Half', path: '/models/kenney-medieval/wall-fortified-gate-half.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_fort_half', name: 'Wall Fort Half', path: '/models/kenney-medieval/wall-fortified-half.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_fort_paint', name: 'Wall Fort Paint', path: '/models/kenney-medieval/wall-fortified-paint.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_fort_paint_d', name: 'Wall Fort Paint Door', path: '/models/kenney-medieval/wall-fortified-paint-door.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_fort_paint_g', name: 'Wall Fort Paint Gate', path: '/models/kenney-medieval/wall-fortified-paint-gate.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_fort_paint_h', name: 'Wall Fort Paint Half', path: '/models/kenney-medieval/wall-fortified-paint-half.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_fort_paint_w', name: 'Wall Fort Paint Window', path: '/models/kenney-medieval/wall-fortified-paint-window.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_fort_window', name: 'Wall Fort Window', path: '/models/kenney-medieval/wall-fortified-window.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_gate', name: 'Wall Gate', path: '/models/kenney-medieval/wall-gate.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_gate_half', name: 'Wall Gate Half', path: '/models/kenney-medieval/wall-gate-half.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_half', name: 'Wall Half', path: '/models/kenney-medieval/wall-half.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_low', name: 'Wall Low', path: '/models/kenney-medieval/wall-low.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_paint', name: 'Wall Paint', path: '/models/kenney-medieval/wall-paint.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_paint_detail', name: 'Wall Paint Detail', path: '/models/kenney-medieval/wall-paint-detail.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_paint_door', name: 'Wall Paint Door', path: '/models/kenney-medieval/wall-paint-door.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_paint_flat', name: 'Wall Paint Flat', path: '/models/kenney-medieval/wall-paint-flat.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_paint_gate', name: 'Wall Paint Gate', path: '/models/kenney-medieval/wall-paint-gate.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_paint_half', name: 'Wall Paint Half', path: '/models/kenney-medieval/wall-paint-half.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_paint_window', name: 'Wall Paint Window', path: '/models/kenney-medieval/wall-paint-window.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_pane', name: 'Wall Pane', path: '/models/kenney-medieval/wall-pane.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_pane_door', name: 'Wall Pane Door', path: '/models/kenney-medieval/wall-pane-door.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_pane_paint', name: 'Wall Pane Paint', path: '/models/kenney-medieval/wall-pane-paint.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_pane_paint_d', name: 'Wall Pane Paint Door', path: '/models/kenney-medieval/wall-pane-paint-door.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_pane_paint_w', name: 'Wall Pane Paint Window', path: '/models/kenney-medieval/wall-pane-paint-window.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_pane_pw', name: 'Wall Pane Painted Wood', path: '/models/kenney-medieval/wall-pane-painted-wood.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_pane_pw_d', name: 'Wall Pane PW Door', path: '/models/kenney-medieval/wall-pane-painted-wood-door.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_pane_pw_w', name: 'Wall Pane PW Window', path: '/models/kenney-medieval/wall-pane-painted-wood-window.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_pane_window', name: 'Wall Pane Window', path: '/models/kenney-medieval/wall-pane-window.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_pane_wood', name: 'Wall Pane Wood', path: '/models/kenney-medieval/wall-pane-wood.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_pane_wood_d', name: 'Wall Pane Wood Door', path: '/models/kenney-medieval/wall-pane-wood-door.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_pane_wood_w', name: 'Wall Pane Wood Window', path: '/models/kenney-medieval/wall-pane-wood-window.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wall_window', name: 'Wall Window', path: '/models/kenney-medieval/wall-window.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_water', name: 'Water', path: '/models/kenney-medieval/water.glb', category: 'nature', defaultScale: 2 },
  { id: 'km_wood_floor', name: 'Wood Floor', path: '/models/kenney-medieval/wood-floor.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wood_floor_half', name: 'Wood Floor Half', path: '/models/kenney-medieval/wood-floor-half.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wood_floor_quarter', name: 'Wood Floor Quarter', path: '/models/kenney-medieval/wood-floor-quarter.glb', category: 'medieval', defaultScale: 2 },
  { id: 'km_wood_floor_rail', name: 'Wood Floor Railing', path: '/models/kenney-medieval/wood-floor-railing.glb', category: 'medieval', defaultScale: 2 },

  // ─═══─ URBAN (Kenney Retro Urban Kit — 124 GLBs, CC0) ─═══─
  { id: 'ku_balcony_ladder_b', name: 'Balcony Ladder Bottom', path: '/models/kenney-urban/balcony-ladder-bottom.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_balcony_ladder_t', name: 'Balcony Ladder Top', path: '/models/kenney-urban/balcony-ladder-top.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_balcony', name: 'Balcony', path: '/models/kenney-urban/balcony-type-a.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_cliff_corner', name: 'Cliff Corner', path: '/models/kenney-urban/cliff-corner.glb', category: 'nature', defaultScale: 2 },
  { id: 'ku_cliff_side', name: 'Cliff Side', path: '/models/kenney-urban/cliff-side.glb', category: 'nature', defaultScale: 2 },
  { id: 'ku_awning_small', name: 'Awning Small', path: '/models/kenney-urban/detail-awning-small.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_awning_wide', name: 'Awning Wide', path: '/models/kenney-urban/detail-awning-wide.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_barrier_strong_d', name: 'Barrier Strong Damaged', path: '/models/kenney-urban/detail-barrier-strong-damaged.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_barrier_strong_a', name: 'Barrier Strong A', path: '/models/kenney-urban/detail-barrier-strong-type-a.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_barrier_strong_b', name: 'Barrier Strong B', path: '/models/kenney-urban/detail-barrier-strong-type-b.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_barrier_a', name: 'Barrier A', path: '/models/kenney-urban/detail-barrier-type-a.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_barrier_b', name: 'Barrier B', path: '/models/kenney-urban/detail-barrier-type-b.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_beam', name: 'Beam', path: '/models/kenney-urban/detail-beam.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_bench', name: 'Bench', path: '/models/kenney-urban/detail-bench.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_block', name: 'Block', path: '/models/kenney-urban/detail-block.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_bricks_a', name: 'Bricks A', path: '/models/kenney-urban/detail-bricks-type-a.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_bricks_b', name: 'Bricks B', path: '/models/kenney-urban/detail-bricks-type-b.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_cables_a', name: 'Cables A', path: '/models/kenney-urban/detail-cables-type-a.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_cables_b', name: 'Cables B', path: '/models/kenney-urban/detail-cables-type-b.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_dumpster_closed', name: 'Dumpster Closed', path: '/models/kenney-urban/detail-dumpster-closed.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_dumpster_open', name: 'Dumpster Open', path: '/models/kenney-urban/detail-dumpster-open.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_light_double', name: 'Street Light Double', path: '/models/kenney-urban/detail-light-double.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_light_single', name: 'Street Light Single', path: '/models/kenney-urban/detail-light-single.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_traffic_light', name: 'Traffic Light', path: '/models/kenney-urban/detail-light-traffic.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_door_a', name: 'Door A', path: '/models/kenney-urban/door-type-a.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_door_b', name: 'Door B', path: '/models/kenney-urban/door-type-b.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_grass', name: 'Grass', path: '/models/kenney-urban/grass.glb', category: 'nature', defaultScale: 2 },
  { id: 'ku_grass_corner', name: 'Grass Corner', path: '/models/kenney-urban/grass-corner.glb', category: 'nature', defaultScale: 2 },
  { id: 'ku_grass_corner_in', name: 'Grass Corner Inner', path: '/models/kenney-urban/grass-corner-inner.glb', category: 'nature', defaultScale: 2 },
  { id: 'ku_grass_hill', name: 'Grass Hill', path: '/models/kenney-urban/grass-hill.glb', category: 'nature', defaultScale: 2 },
  { id: 'ku_pallet', name: 'Pallet', path: '/models/kenney-urban/pallet.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_pallet_small', name: 'Pallet Small', path: '/models/kenney-urban/pallet-small.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_planks', name: 'Planks', path: '/models/kenney-urban/planks.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_road_center', name: 'Road Center', path: '/models/kenney-urban/road-asphalt-center.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_road_corner', name: 'Road Corner', path: '/models/kenney-urban/road-asphalt-corner.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_road_corner_in', name: 'Road Corner Inner', path: '/models/kenney-urban/road-asphalt-corner-inner.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_road_corner_out', name: 'Road Corner Outer', path: '/models/kenney-urban/road-asphalt-corner-outer.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_road_damaged', name: 'Road Damaged', path: '/models/kenney-urban/road-asphalt-damaged.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_road_pavement', name: 'Road Pavement', path: '/models/kenney-urban/road-asphalt-pavement.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_road_side', name: 'Road Side', path: '/models/kenney-urban/road-asphalt-side.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_road_straight', name: 'Road Straight', path: '/models/kenney-urban/road-asphalt-straight.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_dirt_center', name: 'Dirt Road Center', path: '/models/kenney-urban/road-dirt-center.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_dirt_corner', name: 'Dirt Road Corner', path: '/models/kenney-urban/road-dirt-corner.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_dirt_corner_in', name: 'Dirt Road Corner In', path: '/models/kenney-urban/road-dirt-corner-inner.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_dirt_corner_out', name: 'Dirt Road Corner Out', path: '/models/kenney-urban/road-dirt-corner-outer.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_dirt_damaged', name: 'Dirt Road Damaged', path: '/models/kenney-urban/road-dirt-damaged.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_dirt_pavement', name: 'Dirt Pavement', path: '/models/kenney-urban/road-dirt-pavement.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_dirt_side', name: 'Dirt Road Side', path: '/models/kenney-urban/road-dirt-side.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_dirt_straight', name: 'Dirt Road Straight', path: '/models/kenney-urban/road-dirt-straight.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_dirt_tile', name: 'Dirt Tile', path: '/models/kenney-urban/road-dirt-tile.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_roof_metal_poles', name: 'Roof Metal Poles', path: '/models/kenney-urban/roof-metal-poles.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_roof_metal_a', name: 'Roof Metal A', path: '/models/kenney-urban/roof-metal-type-a.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_roof_metal_b', name: 'Roof Metal B', path: '/models/kenney-urban/roof-metal-type-b.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_scaffolding_floor', name: 'Scaffolding Floor', path: '/models/kenney-urban/scaffolding-floor.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_scaffolding_poles', name: 'Scaffolding Poles', path: '/models/kenney-urban/scaffolding-poles.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_scaffolding', name: 'Scaffolding', path: '/models/kenney-urban/scaffolding-structure.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_tree_large', name: 'Tree Large', path: '/models/kenney-urban/tree-large.glb', category: 'nature', defaultScale: 2 },
  { id: 'ku_tree_park', name: 'Park Tree', path: '/models/kenney-urban/tree-park-large.glb', category: 'nature', defaultScale: 2 },
  { id: 'ku_tree_park_pine', name: 'Park Pine', path: '/models/kenney-urban/tree-park-pine-large.glb', category: 'nature', defaultScale: 2 },
  { id: 'ku_tree_pine', name: 'Pine Large', path: '/models/kenney-urban/tree-pine-large.glb', category: 'nature', defaultScale: 2 },
  { id: 'ku_tree_pine_small', name: 'Pine Small', path: '/models/kenney-urban/tree-pine-small.glb', category: 'nature', defaultScale: 2 },
  { id: 'ku_shrub', name: 'Shrub', path: '/models/kenney-urban/tree-shrub.glb', category: 'nature', defaultScale: 2 },
  { id: 'ku_tree_small', name: 'Tree Small', path: '/models/kenney-urban/tree-small.glb', category: 'nature', defaultScale: 2 },
  { id: 'ku_truck_flat', name: 'Truck Flatbed', path: '/models/kenney-urban/truck-flat.glb', category: 'vehicles', defaultScale: 2 },
  { id: 'ku_truck_green', name: 'Truck Green', path: '/models/kenney-urban/truck-green.glb', category: 'vehicles', defaultScale: 2 },
  { id: 'ku_truck_green_cargo', name: 'Truck Green Cargo', path: '/models/kenney-urban/truck-green-cargo.glb', category: 'vehicles', defaultScale: 2 },
  { id: 'ku_truck_grey', name: 'Truck Grey', path: '/models/kenney-urban/truck-grey.glb', category: 'vehicles', defaultScale: 2 },
  { id: 'ku_truck_grey_cargo', name: 'Truck Grey Cargo', path: '/models/kenney-urban/truck-grey-cargo.glb', category: 'vehicles', defaultScale: 2 },
  { id: 'ku_wall_a', name: 'Wall A', path: '/models/kenney-urban/wall-a.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_col', name: 'Wall A Column', path: '/models/kenney-urban/wall-a-column.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_col_p', name: 'Wall A Column Painted', path: '/models/kenney-urban/wall-a-column-painted.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_corner', name: 'Wall A Corner', path: '/models/kenney-urban/wall-a-corner.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_corner_p', name: 'Wall A Corner Painted', path: '/models/kenney-urban/wall-a-corner-painted.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_detail', name: 'Wall A Detail', path: '/models/kenney-urban/wall-a-detail.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_detail_p', name: 'Wall A Detail Painted', path: '/models/kenney-urban/wall-a-detail-painted.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_diag', name: 'Wall A Diagonal', path: '/models/kenney-urban/wall-a-diagonal.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_door', name: 'Wall A Door', path: '/models/kenney-urban/wall-a-door.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_flat', name: 'Wall A Flat', path: '/models/kenney-urban/wall-a-flat.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_flat_gar', name: 'Wall A Flat Garage', path: '/models/kenney-urban/wall-a-flat-garage.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_flat_p', name: 'Wall A Flat Painted', path: '/models/kenney-urban/wall-a-flat-painted.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_flat_win', name: 'Wall A Flat Window', path: '/models/kenney-urban/wall-a-flat-window.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_garage', name: 'Wall A Garage', path: '/models/kenney-urban/wall-a-garage.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_low', name: 'Wall A Low', path: '/models/kenney-urban/wall-a-low.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_low_p', name: 'Wall A Low Painted', path: '/models/kenney-urban/wall-a-low-painted.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_open', name: 'Wall A Open', path: '/models/kenney-urban/wall-a-open.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_painted', name: 'Wall A Painted', path: '/models/kenney-urban/wall-a-painted.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_p_diag', name: 'Wall A Painted Diagonal', path: '/models/kenney-urban/wall-a-painted-diagonal.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_roof', name: 'Wall A Roof', path: '/models/kenney-urban/wall-a-roof.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_roof_det', name: 'Wall A Roof Detailed', path: '/models/kenney-urban/wall-a-roof-detailed.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_roof_sl', name: 'Wall A Roof Slant', path: '/models/kenney-urban/wall-a-roof-slant.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_roof_sl_d', name: 'Wall A Roof Slant Det', path: '/models/kenney-urban/wall-a-roof-slant-detailed.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_a_window', name: 'Wall A Window', path: '/models/kenney-urban/wall-a-window.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b', name: 'Wall B', path: '/models/kenney-urban/wall-b.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_col', name: 'Wall B Column', path: '/models/kenney-urban/wall-b-column.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_corner', name: 'Wall B Corner', path: '/models/kenney-urban/wall-b-corner.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_detail_p', name: 'Wall B Detail Painted', path: '/models/kenney-urban/wall-b-detail-painted.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_diag', name: 'Wall B Diagonal', path: '/models/kenney-urban/wall-b-diagonal.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_door', name: 'Wall B Door', path: '/models/kenney-urban/wall-b-door.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_flat', name: 'Wall B Flat', path: '/models/kenney-urban/wall-b-flat.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_flat_gar', name: 'Wall B Flat Garage', path: '/models/kenney-urban/wall-b-flat-garage.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_flat_win', name: 'Wall B Flat Window', path: '/models/kenney-urban/wall-b-flat-window.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_garage', name: 'Wall B Garage', path: '/models/kenney-urban/wall-b-garage.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_low', name: 'Wall B Low', path: '/models/kenney-urban/wall-b-low.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_open', name: 'Wall B Open', path: '/models/kenney-urban/wall-b-open.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_roof', name: 'Wall B Roof', path: '/models/kenney-urban/wall-b-roof.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_roof_det', name: 'Wall B Roof Detailed', path: '/models/kenney-urban/wall-b-roof-detailed.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_roof_sl', name: 'Wall B Roof Slant', path: '/models/kenney-urban/wall-b-roof-slant.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_roof_sl_d', name: 'Wall B Roof Slant Det', path: '/models/kenney-urban/wall-b-roof-slant-detailed.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_b_window', name: 'Wall B Window', path: '/models/kenney-urban/wall-b-window.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_broken_a', name: 'Wall Broken A', path: '/models/kenney-urban/wall-broken-type-a.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_broken_b', name: 'Wall Broken B', path: '/models/kenney-urban/wall-broken-type-b.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_c_flat', name: 'Wall C Flat', path: '/models/kenney-urban/wall-c-flat.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_c_flat_low', name: 'Wall C Flat Low', path: '/models/kenney-urban/wall-c-flat-low.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_fence', name: 'Wall Fence', path: '/models/kenney-urban/wall-fence.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_steps_a', name: 'Wall Steps A', path: '/models/kenney-urban/wall-steps-type-a.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_steps_b', name: 'Wall Steps B', path: '/models/kenney-urban/wall-steps-type-b.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_type_a', name: 'Wall Type A', path: '/models/kenney-urban/wall-type-a.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_wall_type_b', name: 'Wall Type B', path: '/models/kenney-urban/wall-type-b.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_window_sm_a', name: 'Window Small A', path: '/models/kenney-urban/window-small-type-a.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_window_sm_b', name: 'Window Small B', path: '/models/kenney-urban/window-small-type-b.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_window_wide_a', name: 'Window Wide A', path: '/models/kenney-urban/window-wide-type-a.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_window_wide_b', name: 'Window Wide B', path: '/models/kenney-urban/window-wide-type-b.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_window_wide_c', name: 'Window Wide C', path: '/models/kenney-urban/window-wide-type-c.glb', category: 'urban', defaultScale: 2 },
  { id: 'ku_window_wide_d', name: 'Window Wide D', path: '/models/kenney-urban/window-wide-type-d.glb', category: 'urban', defaultScale: 2 },

  // ─═══─ CHARACTERS (Quaternius, various) ─═══─
  { id: 'char_leela', name: 'Leela', path: '/models/characters/Leela.gltf', category: 'character', defaultScale: 1.5 },
  { id: 'char_mike', name: 'Mike', path: '/models/characters/Mike.gltf', category: 'character', defaultScale: 1.5 },
  { id: 'char_george', name: 'George', path: '/models/characters/George.gltf', category: 'character', defaultScale: 1.5 },
  { id: 'char_stan', name: 'Stan', path: '/models/characters/Stan.gltf', category: 'character', defaultScale: 1.5 },

  // ─═══─ FURNITURE (Kenney Furniture Kit, CC0) ─═══─
  { id: 'kf_bathroom_cabinet', name: 'Bathroom Cabinet', path: '/models/kenney-furniture/bathroomCabinet.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bathroom_cabinet_drawer', name: 'Bathroom Cabinet Drawer', path: '/models/kenney-furniture/bathroomCabinetDrawer.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bathroom_mirror', name: 'Bathroom Mirror', path: '/models/kenney-furniture/bathroomMirror.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bathroom_sink', name: 'Bathroom Sink', path: '/models/kenney-furniture/bathroomSink.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bathroom_sink_square', name: 'Bathroom Sink Square', path: '/models/kenney-furniture/bathroomSinkSquare.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bathtub', name: 'Bathtub', path: '/models/kenney-furniture/bathtub.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bear', name: 'Bear', path: '/models/kenney-furniture/bear.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bed_bunk', name: 'Bed Bunk', path: '/models/kenney-furniture/bedBunk.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bed_double', name: 'Bed Double', path: '/models/kenney-furniture/bedDouble.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bed_single', name: 'Bed Single', path: '/models/kenney-furniture/bedSingle.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bench', name: 'Bench', path: '/models/kenney-furniture/bench.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bench_cushion', name: 'Bench Cushion', path: '/models/kenney-furniture/benchCushion.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bench_cushion_low', name: 'Bench Cushion Low', path: '/models/kenney-furniture/benchCushionLow.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bookcase_closed', name: 'Bookcase Closed', path: '/models/kenney-furniture/bookcaseClosed.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bookcase_closed_doors', name: 'Bookcase Closed Doors', path: '/models/kenney-furniture/bookcaseClosedDoors.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bookcase_closed_wide', name: 'Bookcase Closed Wide', path: '/models/kenney-furniture/bookcaseClosedWide.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bookcase_open', name: 'Bookcase Open', path: '/models/kenney-furniture/bookcaseOpen.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_bookcase_open_low', name: 'Bookcase Open Low', path: '/models/kenney-furniture/bookcaseOpenLow.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_books', name: 'Books', path: '/models/kenney-furniture/books.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_cabinet_bed', name: 'Cabinet Bed', path: '/models/kenney-furniture/cabinetBed.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_cabinet_bed_drawer', name: 'Cabinet Bed Drawer', path: '/models/kenney-furniture/cabinetBedDrawer.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_cabinet_bed_drawer_table', name: 'Cabinet Bed Drawer Table', path: '/models/kenney-furniture/cabinetBedDrawerTable.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_cabinet_television', name: 'Cabinet Television', path: '/models/kenney-furniture/cabinetTelevision.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_cabinet_television_doors', name: 'Cabinet Television Doors', path: '/models/kenney-furniture/cabinetTelevisionDoors.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_cardboard_box_closed', name: 'Cardboard Box Closed', path: '/models/kenney-furniture/cardboardBoxClosed.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_cardboard_box_open', name: 'Cardboard Box Open', path: '/models/kenney-furniture/cardboardBoxOpen.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_ceiling_fan', name: 'Ceiling Fan', path: '/models/kenney-furniture/ceilingFan.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_chair', name: 'Chair', path: '/models/kenney-furniture/chair.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_chair_cushion', name: 'Chair Cushion', path: '/models/kenney-furniture/chairCushion.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_chair_desk', name: 'Chair Desk', path: '/models/kenney-furniture/chairDesk.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_chair_modern_cushion', name: 'Chair Modern Cushion', path: '/models/kenney-furniture/chairModernCushion.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_chair_modern_frame_cushion', name: 'Chair Modern Frame Cushion', path: '/models/kenney-furniture/chairModernFrameCushion.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_chair_rounded', name: 'Chair Rounded', path: '/models/kenney-furniture/chairRounded.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_coat_rack', name: 'Coat Rack', path: '/models/kenney-furniture/coatRack.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_coat_rack_standing', name: 'Coat Rack Standing', path: '/models/kenney-furniture/coatRackStanding.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_computer_keyboard', name: 'Computer Keyboard', path: '/models/kenney-furniture/computerKeyboard.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_computer_mouse', name: 'Computer Mouse', path: '/models/kenney-furniture/computerMouse.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_computer_screen', name: 'Computer Screen', path: '/models/kenney-furniture/computerScreen.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_desk', name: 'Desk', path: '/models/kenney-furniture/desk.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_desk_corner', name: 'Desk Corner', path: '/models/kenney-furniture/deskCorner.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_doorway', name: 'Doorway', path: '/models/kenney-furniture/doorway.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_doorway_front', name: 'Doorway Front', path: '/models/kenney-furniture/doorwayFront.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_doorway_open', name: 'Doorway Open', path: '/models/kenney-furniture/doorwayOpen.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_dryer', name: 'Dryer', path: '/models/kenney-furniture/dryer.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_floor_corner', name: 'Floor Corner', path: '/models/kenney-furniture/floorCorner.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_floor_corner_round', name: 'Floor Corner Round', path: '/models/kenney-furniture/floorCornerRound.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_floor_full', name: 'Floor Full', path: '/models/kenney-furniture/floorFull.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_floor_half', name: 'Floor Half', path: '/models/kenney-furniture/floorHalf.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_hood_large', name: 'Hood Large', path: '/models/kenney-furniture/hoodLarge.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_hood_modern', name: 'Hood Modern', path: '/models/kenney-furniture/hoodModern.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_bar', name: 'Kitchen Bar', path: '/models/kenney-furniture/kitchenBar.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_bar_end', name: 'Kitchen Bar End', path: '/models/kenney-furniture/kitchenBarEnd.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_blender', name: 'Kitchen Blender', path: '/models/kenney-furniture/kitchenBlender.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_cabinet', name: 'Kitchen Cabinet', path: '/models/kenney-furniture/kitchenCabinet.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_cabinet_corner_inner', name: 'Kitchen Cabinet Corner Inner', path: '/models/kenney-furniture/kitchenCabinetCornerInner.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_cabinet_corner_round', name: 'Kitchen Cabinet Corner Round', path: '/models/kenney-furniture/kitchenCabinetCornerRound.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_cabinet_drawer', name: 'Kitchen Cabinet Drawer', path: '/models/kenney-furniture/kitchenCabinetDrawer.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_cabinet_upper', name: 'Kitchen Cabinet Upper', path: '/models/kenney-furniture/kitchenCabinetUpper.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_cabinet_upper_corner', name: 'Kitchen Cabinet Upper Corner', path: '/models/kenney-furniture/kitchenCabinetUpperCorner.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_cabinet_upper_double', name: 'Kitchen Cabinet Upper Double', path: '/models/kenney-furniture/kitchenCabinetUpperDouble.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_cabinet_upper_low', name: 'Kitchen Cabinet Upper Low', path: '/models/kenney-furniture/kitchenCabinetUpperLow.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_coffee_machine', name: 'Kitchen Coffee Machine', path: '/models/kenney-furniture/kitchenCoffeeMachine.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_fridge', name: 'Kitchen Fridge', path: '/models/kenney-furniture/kitchenFridge.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_fridge_built_in', name: 'Kitchen Fridge Built In', path: '/models/kenney-furniture/kitchenFridgeBuiltIn.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_fridge_large', name: 'Kitchen Fridge Large', path: '/models/kenney-furniture/kitchenFridgeLarge.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_fridge_small', name: 'Kitchen Fridge Small', path: '/models/kenney-furniture/kitchenFridgeSmall.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_microwave', name: 'Kitchen Microwave', path: '/models/kenney-furniture/kitchenMicrowave.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_sink', name: 'Kitchen Sink', path: '/models/kenney-furniture/kitchenSink.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_stove', name: 'Kitchen Stove', path: '/models/kenney-furniture/kitchenStove.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_kitchen_stove_electric', name: 'Kitchen Stove Electric', path: '/models/kenney-furniture/kitchenStoveElectric.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lamp_round_floor', name: 'Lamp Round Floor', path: '/models/kenney-furniture/lampRoundFloor.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lamp_round_table', name: 'Lamp Round Table', path: '/models/kenney-furniture/lampRoundTable.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lamp_square_ceiling', name: 'Lamp Square Ceiling', path: '/models/kenney-furniture/lampSquareCeiling.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lamp_square_floor', name: 'Lamp Square Floor', path: '/models/kenney-furniture/lampSquareFloor.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lamp_square_table', name: 'Lamp Square Table', path: '/models/kenney-furniture/lampSquareTable.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lamp_wall', name: 'Lamp Wall', path: '/models/kenney-furniture/lampWall.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_laptop', name: 'Laptop', path: '/models/kenney-furniture/laptop.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lounge_chair', name: 'Lounge Chair', path: '/models/kenney-furniture/loungeChair.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lounge_chair_relax', name: 'Lounge Chair Relax', path: '/models/kenney-furniture/loungeChairRelax.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lounge_design_chair', name: 'Lounge Design Chair', path: '/models/kenney-furniture/loungeDesignChair.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lounge_design_sofa', name: 'Lounge Design Sofa', path: '/models/kenney-furniture/loungeDesignSofa.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lounge_design_sofa_corner', name: 'Lounge Design Sofa Corner', path: '/models/kenney-furniture/loungeDesignSofaCorner.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lounge_sofa', name: 'Lounge Sofa', path: '/models/kenney-furniture/loungeSofa.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lounge_sofa_corner', name: 'Lounge Sofa Corner', path: '/models/kenney-furniture/loungeSofaCorner.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lounge_sofa_long', name: 'Lounge Sofa Long', path: '/models/kenney-furniture/loungeSofaLong.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_lounge_sofa_ottoman', name: 'Lounge Sofa Ottoman', path: '/models/kenney-furniture/loungeSofaOttoman.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_paneling', name: 'Paneling', path: '/models/kenney-furniture/paneling.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_pillow', name: 'Pillow', path: '/models/kenney-furniture/pillow.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_pillow_blue', name: 'Pillow Blue', path: '/models/kenney-furniture/pillowBlue.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_pillow_blue_long', name: 'Pillow Blue Long', path: '/models/kenney-furniture/pillowBlueLong.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_pillow_long', name: 'Pillow Long', path: '/models/kenney-furniture/pillowLong.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_plant_small_1', name: 'Plant Small 1', path: '/models/kenney-furniture/plantSmall1.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_plant_small_2', name: 'Plant Small 2', path: '/models/kenney-furniture/plantSmall2.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_plant_small_3', name: 'Plant Small 3', path: '/models/kenney-furniture/plantSmall3.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_potted_plant', name: 'Potted Plant', path: '/models/kenney-furniture/pottedPlant.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_radio', name: 'Radio', path: '/models/kenney-furniture/radio.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_rug_doormat', name: 'Rug Doormat', path: '/models/kenney-furniture/rugDoormat.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_rug_rectangle', name: 'Rug Rectangle', path: '/models/kenney-furniture/rugRectangle.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_rug_round', name: 'Rug Round', path: '/models/kenney-furniture/rugRound.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_rug_rounded', name: 'Rug Rounded', path: '/models/kenney-furniture/rugRounded.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_rug_square', name: 'Rug Square', path: '/models/kenney-furniture/rugSquare.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_shower', name: 'Shower', path: '/models/kenney-furniture/shower.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_shower_round', name: 'Shower Round', path: '/models/kenney-furniture/showerRound.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_side_table', name: 'Side Table', path: '/models/kenney-furniture/sideTable.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_side_table_drawers', name: 'Side Table Drawers', path: '/models/kenney-furniture/sideTableDrawers.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_speaker', name: 'Speaker', path: '/models/kenney-furniture/speaker.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_speaker_small', name: 'Speaker Small', path: '/models/kenney-furniture/speakerSmall.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_stairs', name: 'Stairs', path: '/models/kenney-furniture/stairs.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_stairs_corner', name: 'Stairs Corner', path: '/models/kenney-furniture/stairsCorner.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_stairs_open', name: 'Stairs Open', path: '/models/kenney-furniture/stairsOpen.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_stairs_open_single', name: 'Stairs Open Single', path: '/models/kenney-furniture/stairsOpenSingle.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_stool_bar', name: 'Stool Bar', path: '/models/kenney-furniture/stoolBar.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_stool_bar_square', name: 'Stool Bar Square', path: '/models/kenney-furniture/stoolBarSquare.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_table', name: 'Table', path: '/models/kenney-furniture/table.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_table_cloth', name: 'Table Cloth', path: '/models/kenney-furniture/tableCloth.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_table_coffee', name: 'Table Coffee', path: '/models/kenney-furniture/tableCoffee.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_table_coffee_glass', name: 'Table Coffee Glass', path: '/models/kenney-furniture/tableCoffeeGlass.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_table_coffee_glass_square', name: 'Table Coffee Glass Square', path: '/models/kenney-furniture/tableCoffeeGlassSquare.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_table_coffee_square', name: 'Table Coffee Square', path: '/models/kenney-furniture/tableCoffeeSquare.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_table_cross', name: 'Table Cross', path: '/models/kenney-furniture/tableCross.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_table_cross_cloth', name: 'Table Cross Cloth', path: '/models/kenney-furniture/tableCrossCloth.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_table_glass', name: 'Table Glass', path: '/models/kenney-furniture/tableGlass.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_table_round', name: 'Table Round', path: '/models/kenney-furniture/tableRound.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_television_antenna', name: 'Television Antenna', path: '/models/kenney-furniture/televisionAntenna.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_television_modern', name: 'Television Modern', path: '/models/kenney-furniture/televisionModern.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_television_vintage', name: 'Television Vintage', path: '/models/kenney-furniture/televisionVintage.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_toaster', name: 'Toaster', path: '/models/kenney-furniture/toaster.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_toilet', name: 'Toilet', path: '/models/kenney-furniture/toilet.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_toilet_square', name: 'Toilet Square', path: '/models/kenney-furniture/toiletSquare.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_trashcan', name: 'Trashcan', path: '/models/kenney-furniture/trashcan.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_wall', name: 'Wall', path: '/models/kenney-furniture/wall.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_wall_corner', name: 'Wall Corner', path: '/models/kenney-furniture/wallCorner.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_wall_corner_rond', name: 'Wall Corner Round', path: '/models/kenney-furniture/wallCornerRond.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_wall_doorway', name: 'Wall Doorway', path: '/models/kenney-furniture/wallDoorway.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_wall_doorway_wide', name: 'Wall Doorway Wide', path: '/models/kenney-furniture/wallDoorwayWide.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_wall_half', name: 'Wall Half', path: '/models/kenney-furniture/wallHalf.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_wall_window', name: 'Wall Window', path: '/models/kenney-furniture/wallWindow.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_wall_window_slide', name: 'Wall Window Slide', path: '/models/kenney-furniture/wallWindowSlide.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_washer', name: 'Washer', path: '/models/kenney-furniture/washer.glb', category: 'furniture', defaultScale: 2 },
  { id: 'kf_washer_dryer_stacked', name: 'Washer Dryer Stacked', path: '/models/kenney-furniture/washerDryerStacked.glb', category: 'furniture', defaultScale: 2 },

  // ─═══─ SCI-FI (Quaternius Modular SciFi MegaKit) ─═══─
  { id: 'qs_alien_cyclop', name: 'Alien Cyclop', path: '/models/quaternius-scifi/Aliens/Alien_Cyclop.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_alien_oculichrysalis', name: 'Alien Oculichrysalis', path: '/models/quaternius-scifi/Aliens/Alien_Oculichrysalis.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_alien_scolitex', name: 'Alien Scolitex', path: '/models/quaternius-scifi/Aliens/Alien_Scolitex.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_column_astra', name: 'Column Astra', path: '/models/quaternius-scifi/Columns/Column_Astra.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_column_hollow', name: 'Column Hollow', path: '/models/quaternius-scifi/Columns/Column_Hollow.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_column_pipes', name: 'Column Pipes', path: '/models/quaternius-scifi/Columns/Column_Pipes.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_door_darkmetal', name: 'Door Dark Metal', path: '/models/quaternius-scifi/Platforms/Door_DarkMetal.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_door_metal', name: 'Door Metal', path: '/models/quaternius-scifi/Platforms/Door_Metal.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_platform_rails_4', name: 'Platform Rails', path: '/models/quaternius-scifi/Platforms/Platform_Rails_4.gltf', category: 'scifi', defaultScale: 1 },
  { id: 'qs_platform_ramp_4', name: 'Platform Ramp', path: '/models/quaternius-scifi/Platforms/Platform_Ramp_4.gltf', category: 'scifi', defaultScale: 1 },
  { id: 'qs_platform_stairs_4', name: 'Platform Stairs', path: '/models/quaternius-scifi/Platforms/Platform_Stairs_4.gltf', category: 'scifi', defaultScale: 1 },
  { id: 'qs_platform_round', name: 'Platform Round', path: '/models/quaternius-scifi/Platforms/Platform_Round1.gltf', category: 'scifi', defaultScale: 1 },
  { id: 'qs_prop_computer', name: 'SciFi Computer', path: '/models/quaternius-scifi/Props/Prop_Computer.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_prop_chest', name: 'SciFi Chest', path: '/models/quaternius-scifi/Props/Prop_Chest.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_prop_barrel', name: 'SciFi Barrel', path: '/models/quaternius-scifi/Props/Prop_Barrel_Large.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_prop_crate', name: 'SciFi Crate', path: '/models/quaternius-scifi/Props/Prop_Crate3.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_prop_light_floor', name: 'SciFi Floor Light', path: '/models/quaternius-scifi/Props/Prop_Light_Floor.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_prop_vent_big', name: 'SciFi Vent', path: '/models/quaternius-scifi/Props/Prop_Vent_Big.gltf', category: 'scifi', defaultScale: 1.5 },
  { id: 'qs_prop_access_point', name: 'Access Point', path: '/models/quaternius-scifi/Props/Prop_AccessPoint.gltf', category: 'scifi', defaultScale: 1.5 },

  // ─═══─ FANTASY PROPS (Quaternius Fantasy Props MegaKit) ─═══─
  { id: 'qf_anvil_log', name: 'Anvil on Log', path: '/models/quaternius-fantasy/Anvil_Log.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_barrel', name: 'Fantasy Barrel', path: '/models/quaternius-fantasy/Barrel.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_barrel_apples', name: 'Barrel of Apples', path: '/models/quaternius-fantasy/Barrel_Apples.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_banner_1', name: 'Banner', path: '/models/quaternius-fantasy/Banner_1.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_bookcase', name: 'Bookcase', path: '/models/quaternius-fantasy/Bookcase_2.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_bookstand', name: 'Book Stand', path: '/models/quaternius-fantasy/BookStand.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_cauldron', name: 'Cauldron', path: '/models/quaternius-fantasy/Cauldron.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_chandelier', name: 'Chandelier', path: '/models/quaternius-fantasy/Chandelier.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_chest_wood', name: 'Wooden Chest', path: '/models/quaternius-fantasy/Chest_Wood.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_candlestick_stand', name: 'Candlestick Stand', path: '/models/quaternius-fantasy/CandleStick_Stand.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_cage_small', name: 'Small Cage', path: '/models/quaternius-fantasy/Cage_Small.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_chalice', name: 'Chalice', path: '/models/quaternius-fantasy/Chalice.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_coin_pile', name: 'Coin Pile', path: '/models/quaternius-fantasy/Coin_Pile_2.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_dummy', name: 'Training Dummy', path: '/models/quaternius-fantasy/Dummy.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_lantern_wall', name: 'Wall Lantern', path: '/models/quaternius-fantasy/Lantern_Wall.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_potion_1', name: 'Potion Bottle', path: '/models/quaternius-fantasy/Potion_1.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_shield_wooden', name: 'Wooden Shield', path: '/models/quaternius-fantasy/Shield_Wooden.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_sword_bronze', name: 'Bronze Sword', path: '/models/quaternius-fantasy/Sword_Bronze.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_stall_cart', name: 'Market Cart', path: '/models/quaternius-fantasy/Stall_Cart_Empty.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_stall_empty', name: 'Market Stall', path: '/models/quaternius-fantasy/Stall_Empty.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_table_large', name: 'Large Table', path: '/models/quaternius-fantasy/Table_Large.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_torch_metal', name: 'Metal Torch', path: '/models/quaternius-fantasy/Torch_Metal.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_weapon_stand', name: 'Weapon Stand', path: '/models/quaternius-fantasy/WeaponStand.gltf', category: 'fantasy', defaultScale: 1.5 },
  { id: 'qf_workbench', name: 'Workbench', path: '/models/quaternius-fantasy/Workbench.gltf', category: 'fantasy', defaultScale: 1.5 },

  // ─═══─ MEDIEVAL VILLAGE (Quaternius Medieval Village MegaKit) ─═══─
  { id: 'qv_wall_plaster', name: 'Village Wall Plaster', path: '/models/quaternius-medieval-village/Wall_Plaster_Straight.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_wall_plaster_door', name: 'Village Wall Door', path: '/models/quaternius-medieval-village/Wall_Plaster_Door_Round.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_wall_plaster_window', name: 'Village Wall Window', path: '/models/quaternius-medieval-village/Wall_Plaster_Window_Wide_Round.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_wall_brick_door', name: 'Brick Wall Door', path: '/models/quaternius-medieval-village/Wall_UnevenBrick_Door_Round.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_wall_arch', name: 'Wall Arch', path: '/models/quaternius-medieval-village/Wall_Arch.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_roof_roundtiles', name: 'Roof Round Tiles', path: '/models/quaternius-medieval-village/Roof_RoundTiles_6x8.gltf', category: 'village', defaultScale: 1 },
  { id: 'qv_roof_dormer', name: 'Roof Dormer', path: '/models/quaternius-medieval-village/Roof_Dormer_RoundTile.gltf', category: 'village', defaultScale: 1 },
  { id: 'qv_roof_tower', name: 'Tower Roof', path: '/models/quaternius-medieval-village/Roof_Tower_RoundTiles.gltf', category: 'village', defaultScale: 1 },
  { id: 'qv_balcony_simple', name: 'Simple Balcony', path: '/models/quaternius-medieval-village/Balcony_Simple_Straight.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_door_round', name: 'Round Door', path: '/models/quaternius-medieval-village/Door_2_Round.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_stairs_exterior', name: 'Exterior Stairs', path: '/models/quaternius-medieval-village/Stairs_Exterior_Straight.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_prop_wagon', name: 'Wagon', path: '/models/quaternius-medieval-village/Prop_Wagon.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_prop_chimney', name: 'Chimney', path: '/models/quaternius-medieval-village/Prop_Chimney.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_prop_crate', name: 'Village Crate', path: '/models/quaternius-medieval-village/Prop_Crate.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_fence_ornament', name: 'Ornament Fence', path: '/models/quaternius-medieval-village/Prop_MetalFence_Ornament.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_fence_wooden', name: 'Wooden Fence', path: '/models/quaternius-medieval-village/Prop_WoodenFence_Single.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_window_shutters_open', name: 'Window Shutters Open', path: '/models/quaternius-medieval-village/WindowShutters_Wide_Round_Open.gltf', category: 'village', defaultScale: 1.5 },
  { id: 'qv_vine', name: 'Wall Vine', path: '/models/quaternius-medieval-village/Prop_Vine1.gltf', category: 'village', defaultScale: 1.5 },

  // ═══ AVATARS — VRM characters from opensourceavatars.com (CC0) ═══
  { id: 'av_orion', name: 'Orion', path: '/avatars/gallery/Orion.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_cool_alien', name: 'Cool Alien', path: '/avatars/gallery/CoolAlien.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_binky', name: 'Binky Cranberry', path: '/avatars/gallery/Binky_Cranberry.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_mushy', name: 'Mushy', path: '/avatars/gallery/Mushy.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_vipe_2723', name: 'VIPE Hero 2723', path: '/avatars/gallery/VIPE_Hero__2723.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_vipe_2784', name: 'VIPE Hero 2784', path: '/avatars/gallery/VIPE_Hero__2784.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_vipe_2799', name: 'VIPE Hero 2799', path: '/avatars/gallery/VIPE_Hero__2799.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_munch', name: 'Munch Gingerbread', path: '/avatars/gallery/Munch_Gingerbread.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_gary', name: 'Gary Grifter', path: '/avatars/gallery/GARY_GRIFTER_1_0.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_steamboat', name: 'Steamboat Summer', path: '/avatars/gallery/STEAMBOAT_SUMMER.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_eye_diviner', name: 'Eye Diviner', path: '/avatars/gallery/EYE_Diviner.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_king_mutatio', name: 'King Mutatio', path: '/avatars/gallery/King_Mutatio.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_crustybutt', name: 'Crustybutt da King', path: '/avatars/gallery/Crustybutt_da_king.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_harvester', name: 'Harvester Summer', path: '/avatars/gallery/Harvester__Summer.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_esktix', name: 'Esktix Magma', path: '/avatars/gallery/Esktix__Magma.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_grifter_squad', name: 'Grifter Squaddie', path: '/avatars/gallery/Grifter_Squaddie__764.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_mimic_slime', name: 'Mimic Slime', path: '/avatars/gallery/Mimic_Slime__Classic.vrm', category: 'avatar', defaultScale: 1 },
  { id: 'av_the_worm', name: 'The Worm', path: '/avatars/gallery/The_Worm.vrm', category: 'avatar', defaultScale: 1 },
]
